### PR TITLE
Gyanendra dev

### PR DESCRIPTION
**Pull request by devGyan**

### CODE REVIEW

**Comment by eralpsahin** [comment]
> @devGyan @eralpsahin I am unable to login. Eralp can you have a look?

I've just checked and was able to login without any problems. What problem are you getting? Does the spinner get stuck after clicking Log In?

**Comment by rhk12** [comment]
> > @devGyan @eralpsahin I am unable to login. Eralp can you have a look?
> 
> I've just checked and was able to login without any problems. What problem are you getting? Does the spinner get stuck after clicking Log In?

it is working now. not sure what was the issue.

**Comment by rhk12** [comment]
- @devGyan @eralpsahin there are merge conflicts. please fix.

**Comment by devGyan** [comment]
Successfully resolved conflict, you can add now.

**Pull request merged**
