### PR TITLE
Resolve conflict

### PR DESCRIPTION
**Pull request by devGyan**

### CODE REVIEW

**Comment by rhk12** [comment]
@vradars can you check that this pull request is no overwriting the work you committed yesterday?

**Comment by vradars** [comment]
> @vradars can you check that this pull request is no overwriting the work you committed yesterday?

Sure I will check the code, And will update here.

**Comment by rhk12** [comment]
@devGyan @vradars Code does not run for me. I cannot log in to profile section. Dashboad does not show anything

**Comment by devGyan** [comment]
@vradars,
 is it working for you?

**Comment by devGyan** [comment]
After taking a pull from this branch into master on my local it is working for me.

**Pull request merged**
